const SET_ITEMS_DATA = 'wins/items/SET_ITEMS_DATA';
const SET_ITEMS_LOADING = 'wins/items/SET_ITEMS_LOADING';
const SET_TOTAL_ITEMS_COUNT = 'wins/items/SET_TOTAL_ITEMS_COUNT';

export default {
  SET_ITEMS_DATA,
  SET_ITEMS_LOADING,
  SET_TOTAL_ITEMS_COUNT,
};
